# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [main]
    types:
      - "closed"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      output_test: ${{ steps.test-step.outputs.test }}
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - id: test-step
        run: echo "test=1234" >> $GITHUB_OUTPUT
  merge_job:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "Your PR is ${{ github.event.number }} !"
      # if: success() && steps.findPr.outputs.number
